[package]
name = "advent_of_code_2025"
version = "0.1.0"
edition = "2024"

[dependencies]
structopt = "0.3.26"
anyhow = "1.0"
humantime = "2.3.0"
owo-colors = "4.2.3"
num = "0.4.1"
itertools = "0.14"
funty = "2.0.0"
lazy_static = "1.5.0"
either = "1.15.0"